//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int RatingId { get; set; }
        public int RatingValueId { get; set; }
        public string User { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ratingvalue ratingvalue { get; set; }
    }
}
